### ISSUE TITLE
`/api` endpoints not picked up when running `vercel dev`

### ISSUE THREAD

**Issue by Strydom** [magne4000/vite-plugin-vercel#35] opened 2023-11-26 17:31 UTC
👋🏻 Hello
Now that I have setup everything through Vercel, I have been trying to get local development to work when using `vercel dev` command.

I have setup the dev command to link to the existing project in vercel and when running `vercel dev` everything loads fine minus this small error...
```
Failed to resolve dependency: cross-fetch, present in 'optimizeDeps.include'
```

When I view a page without api calls the page renders.
When I view a page with api calls I get this error...
```
5:08:16 PM [vike][request(14)] HTTP request: /api/countryScores
5:08:16 PM [vike][request(14)] URL /api/countryScores doesn't match the route of any of your pages:
┌───────────────────────────────────────┬──────────────┬───────────────────────────────────────────────────────────┐
│ ROUTE                                 │ TYPE         │ DEFINED BY                                                │
├───────────────────────────────────────┼──────────────┼───────────────────────────────────────────────────────────┤
│ /                                     │ Route String │ /src/pages/landing/+route.ts > export default   │
│ /country/@countryCode                 │ Route String │ /src/pages/country/+route.ts > export default   │
│ /country/@countryCode/itinerary/@days │ Route String │ /src/pages/itinarary/+route.ts > export default │
│ /discover                             │ Route String │ /src/pages/discover/+route.ts > export default  │
│ /search                               │ Route String │ /src/pages/search/+route.ts > export default    │
└───────────────────────────────────────┴──────────────┴───────────────────────────────────────────────────────────┘
```

My project is setup with a `src` folder and an `_api` folder at the same level.
```
web/
  _api/
    countryScores.ts
  src/
    pages/
    ...
```

Related:
- https://github.com/magne4000/vite-plugin-vercel/issues/19
- https://github.com/magne4000/vite-plugin-vercel/issues/20

**Comment by Strydom** [comment] 2023-11-26 17:49
Switched the file name to `api` and it's working.
Anything you can do for the `_api`?

**Comment by magne4000** [comment] 2023-11-27 10:12
Duplicate of #19

> Anything you can do for the `_api`?

I need to see what can be done to circumvent this. There is a specific issue to track this https://github.com/magne4000/vite-plugin-vercel/issues/20 but I do not have much bandwidth to tackle this for now.

**Closed by magne4000** 2023-11-27 10:12 UTC

**Comment by Strydom** [comment] 2023-11-28 19:16
So `api` works locally but then it breaks the build in Vercel, i guess because of the known double build issues. `_api` works in Vercel.

> but I do not have much bandwidth to tackle this for now.
Completely understand, story of my life.

I have a work around for now, i just have to keep switching between `api` and `_api` when working in different envs.

**Comment by harjot1singh** [comment] 2025-07-06 16:42
For anyone looking, try this for now: https://github.com/magne4000/vite-plugin-vercel/issues/152#issuecomment-3042190001
