### ISSUE TITLE
I don't understand how to use this plugin

### ISSUE THREAD

**Issue by carere** [magne4000/vite-plugin-vercel#15] opened 2023-06-29 00:23 UTC
Hello, I don't understand how to use this plugin, here is my config:
```ts
import react from "@vitejs/plugin-react"
import dotenv from "dotenv"
import { defineConfig } from "vite"
import ssr from "vite-plugin-ssr/plugin"
import vercel from "vite-plugin-vercel"

dotenv.config()

console.log(process.env.VERCEL_ENV)
console.log(process.env.ENABLE_VC_BUILD)

export default defineConfig({
  plugins: [react(), ssr(), vercel()],
  vercel: {
    rewrites: [
      {
        source: "/(.*)",
        destination: "/index.html"
      }
    ]
  },
  define: {
    global: "window"
  }
})
```

I get this error "[vite-plugin-ssr][Wrong Usage] At least one page should be defined, see https://vite-plugin-ssr.com/add"
I just want to build my api functions located in the `api` folder at the root of my project.
When I test the build locally (without the `vite-plugin-ssr`), I don't see any `.vercel/ouput` folder, vite seems to skip tottaly this plugin.
I defined the two env variable after reading your source code, but don't see any improvement...

Do you have any idea ?
Best regards, and thx for all your work :)

**Comment by magne4000** [comment] 2023-06-29 12:49
Seems like your project did not use `vite-plugin-ssr` prior installing `vite-plugin-vercel` right?
`vite-plugin-ssr` is NOT required to use `vite-plugin-vercel`, and in fact you should not have installed it.
So the only thing you should need is the following from the README:
> .[jt]s files under the <root>/api folder of your project are automatically bundled as Serverless functions under .vercel/output/functions/api/*.func

You can also use [additionalEndpoints](https://github.com/magne4000/vite-plugin-vercel/blob/main/packages/vercel/src/types.ts#L47) to fine tune your endpoints.

Let me know if you still have any issues after that.

**Comment by carere** [comment] 2023-06-30 15:16
Hello, I first tried without vite-plugin-ssr, since as you said I only use serverless function and I'm building a SPA, so no SSR.
But the problem is that i don't see any `.vercel/output/` generated in my project, it's like the plugin was inexistent for vite.
My goal is to be able to build my SPA and my Serverless functions before pushin it to vercel, because I on't like how vercel build my functions.

**Comment by magne4000** [comment] 2023-06-30 16:10
There was an issue when not used without `vite-plugin-ssr`, which is fixed in `v0.2.1`.
`.vercel` folder should now be created as intended.

**Comment by carere** [comment] 2023-07-01 15:05
But it does not 😅 That's my problem, Do you have a repo where the `.vercel` folder is actually created ?

**Comment by magne4000** [comment] 2023-07-01 15:22
Just to be sure: I fixed it in `v0.2.1` yesterday, so you need to update if I wasn't clear.

And I indeed added a quick example that you can build in `examples/simple`, and you'll see that it generates `.vercel` folder.

**Comment by carere** [comment] 2023-07-01 18:42
Ok now it's working with the latest version. Since the build is performed by your plugin inside vite, I guess that I just need to use `vercel depoy --prebuilt` and specify output file ?

**Comment by magne4000** [comment] 2023-07-01 19:40
I haven't used the vercel cli for deploying prebuilt project, so I think that's the right way to do it, but le met know if this works as intended, and then I'll probably add that to the README.

**Closed** 2023-07-12 12:00 UTC
