### ISSUE TITLE
/api handlers not being picked up by Vercel deploy

### ISSUE THREAD

**Issue by Strydom** [magne4000/vite-plugin-vercel#33] opened 2023-10-21 13:56 UTC
👋🏻 Hello

It looks like my `/api` routes are not being registers as functions when deploying on vercel.

![image](https://github.com/magne4000/vite-plugin-vercel/assets/2946828/8924335e-8c34-4c0f-ad7e-e4d18b553e80)

```
src/_api/
  api1.ts
  api2.ts
  api3.ts
  ...
```

They all follow this handler patter

```typescript
import type { VercelRequest, VercelResponse } from '@vercel/node'
import { api1 } from 'apis'

export default async function handler(
    request: VercelRequest,
    response: VercelResponse
) {
  const body = request.body

  return response.json(await api1(body))
}
```

**Comment by magne4000** [comment] 2023-10-21 14:10
I will need to check that, it doesn;t seem right. If you have a reproduction repository I can test that quickly

**Comment by magne4000** [comment] 2023-10-22 12:56
I'm unable to reproduce this issue. The `example/demo` which is built and deployed using the plugin have 2 `_api/` endpoints, and I see them both.

![image](https://github.com/magne4000/vite-plugin-vercel/assets/1098371/0edba69e-1c39-436e-a70b-e31897a45069)

Perhaps it was a temporary issue on Vercel's side? Could you check again?

**Comment by Strydom** [comment] 2023-10-24 09:03
I will try and create a repo app for you but I did just followed your [example/demo](https://github.com/magne4000/vite-plugin-vercel/tree/main/examples/demo).

It's odd, everything else is working, except the apis.
I tried adding the most basic GET handler to echo out OK and that doesn't work either.
```typescript
export default async function handler() {
  return new Response("OK")
}
```

I thought maybe it was the additional endpoint stuff i setup to get middleware working, but even after commenting that out it's not working 🤷🏻‍♂️

**Comment by magne4000** [comment] 2023-10-24 09:24
Oh I can already tell you that `/src/_api/` are not taken into account here, only files at `/_api`

**Comment by Strydom** [comment] 2023-10-24 09:47
Ah okay, so if i want it under `src` i have to use `src/api` but that will cause vercel to double build.
Using `_api` can only be done at the root and will not cause double builds.

I guess i can do what i did with the middleware and define my own routes, so that i can have `_api` within `src`?

**Comment by magne4000** [comment] 2023-10-24 10:11
I actually don't know if vercel cli takes into account `/src/api`.
If it's the case, I will support `/src/_api` as well.

Otherwise, dynamically generating `additionalEndpoints` config shouldn't be to difficult I guess

**Comment by magne4000** [comment] 2023-10-24 10:20
FYI this probably will be configurable in the future (i.e. you will be able to tell it which directory contains your api files, or completely disable it). But it will be part of a big refactor, so no ETA.

**Closed** 2023-10-28 12:24 UTC

**Comment by Strydom** [comment] 2023-10-29 11:10
Sorry for the delayed response, I was trying to get things working but am having issues with importing JSON files now.
Moving the `_api` package up to the root worked for getting the apis to register at least 👍🏻

**Comment by magne4000** [comment] 2023-10-29 15:48
Is your api package version bumped when you make a change? Vercel's probably checking if your package.json or lock file has been updated in order to know if it can reuse previous cache or not.
